### ISSUE TITLE
iCalendar not updating in Google Calendar

### ISSUE THREAD

**Issue by jamietanna** [aaronpk/Meetable#115]
It looks like when I updated https://events.indieweb.org/2020/11/homebrew-website-club-nottingham-KVKTja7qiwEW the iCalendar entry was updated, but Google doesn't see it as an update.

Is there anything that we can do our side to force Google / iCalendar readers to see it as an update?

**Comment by aaronpk** [comment]
Google calendar polls the feed on its own schedule, as far as I know there's no way to force it. It should eventually update.
