### ISSUE TITLE
Fix ics feed for Google calendar

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Meetable#138]
Most other calendars send an `Accept: text/calendar` header, but for some reason Google does not send any `Accept` header at all. 

The Google calendar user agent is `Google-Calendar-Importer`

**Comment by samwilson** [comment]
It looks like Fastmail is failing to sync as well.

> Sync with https://events.indieweb.org/ics/events.ics is disabled. Too many failures.

Unfortunately, they don't say what the failures are.

**Comment by aaronpk** [comment]
The change in #139 should fix this.

**Comment by aaronpk** [comment]
Confirmed, I'm able to subscribe in Google Calendar now!
