### ISSUE TITLE
With latest commit (51ce4b2) cannot add to database

### ISSUE THREAD

**Issue by aminvakil** [aaronpk/Meetable#141]
After pulling this commit (https://github.com/aaronpk/Meetable/commit/51ce4b2fd9e644867b8cece355418cd49748f659)

I cannot add an event anymore to meetable.

Any attempt results in " Database Error: Could not connect to database" with "550 No Reason Phrase" http return code.

FYI I'm using mariadb 10.5.12 on Debian 11 Bullseye.

**Comment by aaronpk** [comment]
Make sure you run the migrations after pulling the new code

**Comment by aminvakil** [comment]
Thanks! Running `php artisan migrate` after `git pull` fixed the issue.
