### ISSUE TITLE
Meeting Status for Events that are Not Attendable

### ISSUE THREAD

**Issue by dshanske** [aaronpk/Meetable#159]
Not sure how to phrase the status...But, want to be able to add to the calendar activities...like the recent Indieweb writing challenge to write about cooking and such. 

The net effect would be an icon next to the event on the display that would show that.

**Comment by aaronpk** [comment]
By "not attendable" do you mean not showing RSVPs? What exactly changes based on an event like this?

**Comment by dshanske** [comment]
Well, an example was the Send a Friend a Webmention Day...there is nothing to attend.

**Comment by aaronpk** [comment]
If there is nothing to attend then is it really an event?

**Comment by dshanske** [comment]
An event is a thing that happens.  This also allows for things like the https://sarajaksa.eu/2023/06/carnival-of-indieweb-june-2023-edition-indieweb-and-cooking/ - Carnival of Indiewebs.

**Comment by aaronpk** [comment]
The other way to ask the question is what does it mean to "attend" this kind of event? Clearly if it's worth posting then there's something you do for the event, even if it is not going to a physical or virtual place. So what actually is the difference you're trying to communicate with this kind of event?

**Comment by dshanske** [comment]
Participation over attendance

**Comment by aaronpk** [comment]
so it's a matter of not allowing/showing RSVPs then?

**Comment by dshanske** [comment]
Yes and just posts.

**Comment by capjamesg** [comment]
I like this idea and the flexibility it brings. I would disable RSVPs for events that are not attendable. I am not sure how we can visually distinguish between events that involve getting together vs. events like the IndieWeb Carnival that are happening but don't have a specific meeting venue.

Maybe the homepage could have a key with a calendar emoji. A calendar emoji present next to the event date means there is a call; no emoji means there is not a call?

**Comment by gRegorLove** [comment]
I could see this being useful for an event that represents a deadline, like "Proposal submissions due". The main purpose for it appearing on the calendar is as a reminder, so no RSVPs needed.

Maybe less common for Meetable's typical use, but it could also be useful if anniversaries like "Webmention turns 15", holidays, or other types of all-day events like Send a Friend a Webmention Day.

Being able to toggle the RSVPs off sounds like a good option for these. I'm not sure separate emoji are needed. If there is no physical meeting, then leaving the address empty works. Similarly, if there's no virtual meeting, leaving the videoconferencing field empty.

**Comment by aaronpk** [comment]
It seems like the smallest change we can make is to add a setting on individual events to enable or disable RSVPs. I will open a new issue to track that since there are a few other questions to consider: #162
