### ISSUE TITLE
Somehow solve file storage for Heroku deploys

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Meetable#68]
I forgot to add an S3 setup stage to the installer, which isn't necessary for shared hosting, but Heroku can't store stuff on the filesystem. We should either provision an S3-compatible add-on by default, or find some other Heroku-compatible way to store files, like storing them as binary blobs in the database.

**Comment by aaronpk** [comment]
CloudCube is one potential solution, providing an S3 service as a free add-on

https://elements.heroku.com/addons/cloudcube

It sets these environment variables:

`CLOUDCUBE_ACCESS_KEY_ID` `CLOUDCUBE_SECRET_ACCESS_KEY`

**Comment by Lewiscowles1986** [comment]
I think #69 solves (although has a 5MB limit)

**Comment by aaronpk** [comment]
Yes! That's fantastic! Closing this now since the default Heroku install has a way to store stuff.
