### ISSUE TITLE
Meetable feature request: event cancellation while keeping in list

### ISSUE THREAD

**Issue by tantek** [aaronpk/Meetable#86]
Meetable events should be editable to explicitly cancel them, yet keep them in the list of events (upcoming or past) so it is clear to folks who may have already RSVPd, or have been sent a link to view them that they were canceled.

Use-case: On the IndieWeb wiki we used to explicitly note on the wiki page for the Homebrew Website Club events for a particular day, if and when a particular city/location was canceled, usually by adding strike-through (s tag) or deletion (del tag) markup. This is particularly useful for when an organizer is unable to make it themselves and can’t be sure that anyone else will either.

Display: A canceled event should be explicitly flagged as such in any listings, perhaps with a red CANCELLED label.

Optional name prefix: consider prefixing the editable name of the event with the all-caps "CANCELED: " as part of the marked up p-name of the h-event.

It should also be possible to edit and uncancel an event in case it was canceled accidentally or errantly by someone.

RSVP interaction: a canceled event should no longer accept RSVPs via the user interface, perhaps rejecting federated webmention RSVPs as well.

A canceled event may send Webmentions back to the federated RSVP posts that it is listing (and or perhaps their author domains), so those posts can be updated, and authors notified.

(Originally published at: https://tantek.com/2020/062/b4/)

**Comment by aaronpk** [comment]
Done in https://github.com/aaronpk/Meetable/commit/bd8e4efab7b9abe474b3e33b49d09767cd478b9f
