### ISSUE TITLE
Meetable feature request: create a canceled event

### ISSUE THREAD

**Issue by tantek** [aaronpk/Meetable#87]
This is a feature request to deliberately add a canceled event, i.e. an event that was not previously on Meetable, as a heads-up to folks who may be expecting a regular event and wondering where the information is, or assuming it may still be on at the usual time and place. This is different from [#86](https://github.com/aaronpk/Meetable/issues/86) which is about canceling an existing event.

Use-case: In the IndieWeb community we have several regular Homebrew Website Club (HWC) meetups, some every two weeks, some every month like the first Wednesday of the month. When one of these expectedly periodic events is missing (especially the less frequent ones like first Wednesday of the month, like what just happened with HWC Austin this week), we’re more likely to assume the organizer just forgot to post an official online event, rather than the regular event is not actually happening. Thus we need a way to explicitly create a canceled event when one has not yet been posted.

Editing: have an option to perhaps check when creating an event that this is a "cancelled" event, which means that it will not be accepting RSVPs, perhaps doesn’t need a venue.

Display: Similar to #86, a canceled event should be explicitly flagged as such in any listings, perhaps with a red CANCELLED label. It should also be listed in upcoming and past event listings per its datetime along with other events.

Again similar to #86, optional name prefix: consider prefixing the editable name of the event with the all-caps "CANCELED: " as part of the marked up p-name of the h-event.

It should also be possible to edit and uncancel a canceled event and turn it into a real event in case it turns out to actually be happening, perhaps by another organizer!

RSVP interaction: a canceled event should not accept RSVPs via the user interface, perhaps rejecting federated webmention RSVPs as well.

(Originally published at: https://tantek.com/2020/062/b5/)

**Comment by aaronpk** [comment]
Done in https://github.com/aaronpk/Meetable/commit/bd8e4efab7b9abe474b3e33b49d09767cd478b9f
