### ISSUE TITLE
Add sharing metadata to events

### ISSUE THREAD

**Issue by jamietanna** [aaronpk/Meetable#90]
I found adding sharing metadata to my site quite useful, i.e. https://www.jvt.me/events/homebrew-website-club-nottingham/2020/01/22/:

```xml
<meta name="twitter:description" content="Homebrew Website Club on November 27th.">
<meta name="twitter:label1" value="Start time">
<meta name="twitter:data1" value="Wed, 22 Jan 2020 17:30:00 GMT">
<meta name="twitter:label2" value="Address">
<meta name="twitter:data2" value="72 Maid Marian Way, Nottingham, NG1 6BJ">
<meta name="twitter:image" content="https://www.jvt.me/img/vendor/hwc-80s-retro.jpg">
```

This is primarily used on Slack (despite being for Twitter metadata) and can make it nice when sharing with other folks

**Comment by aaronpk** [comment]
Events already contain `og` tags for this. I'm not familiar with the `twitter:label1`, I don't see those mentioned in the Twitter docs or any docs really.

**Comment by jamietanna** [comment]
Yeah, that's interesting, I've definitely seen it used by Slack when i.e. sharing my event URLs, I'm not sure why it's under Twitter if it's not used.

**Comment by aaronpk** [comment]
You should be seeing some amount of unfurling happening in Slack already, since Slack does read the og meta tags too. If you can point to any docs on the `twitter:label1` and such I can take a look, but I don't want to just go adding random crap.

**Comment by jamietanna** [comment]
Unfortunately seeing it only unfurling the image: 

![2020-04-18-194912_1039x656_scrot](https://user-images.githubusercontent.com/3315059/79666731-b5f0bd80-81ad-11ea-99ee-a86fa67c6922.png)

That's fair, but as you say I can't find any official docs for it. According to https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254 it was for the "Product card", which has now been deprecated, but still appears to be used by a few places, including Slack, even thought Twitter doesn't use it.
