### ISSUE TITLE
Nested events, or sessions within an event

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Meetable#91]
Examples:

https://events.oauth.net/2019/11/ietf-106-singapore-3svpgayqD1he

* One multi-day event with sub-events at individual times

https://2020.indieweb.org/london

* For a virtual conference, each session will have specific info such as a Zoom link, and needs to be able to show localized times easily

**Comment by dshanske** [comment]
Isn't the simplest implementation just a parent property so that any event with the parent property will display and nest under the parent event?
