### ISSUE TITLE
Meetable should sort events on the same day by their UTC time

### ISSUE THREAD

**Issue by tantek** [aaronpk/Meetable#93]
Meetable clusters events in the same month under a common heading for that month, and shows events in date order, regardless of location. Events on the same day with a specified start time should be sorted by the UTC value of their time, so they’re listed in absolute temporal order.

For example, the [events on 2020-04-08](https://events.indieweb.org/2020/04/08) are almost sorted by UTC time order, however, Online HWC Karlsruhe Europe/Berlin 18:30 (UTC 16:30) should be listed before Online HWC Europe/London 18:00 (UTC 17:00), whereas currently the London event is listed first.

Listing events in absolute temporal order is particularly useful when the majority (or all) of the events are online and thus potentially available and open to people outside the specified time zone of the event, especially an adjacent time zone.

(Originally published at: https://tantek.com/2020/097/b1/meetable-sort-same-day-events-utc-time)

**Comment by aaronpk** [comment]
What should happen if an event is not listed with a timezone? I suppose defaulting to UTC is probably the best bet?

**Comment by aaronpk** [comment]
Implemented this by assuming UTC if no timezone is present. We can decide whether that's appropriate later in a new issue.
